typedef char (*t_lineaddress)[LINES];
void ft_error_met(char *message);
void ft_init_lineaddress(char *(*lineaddress)[LINES]);
void ft_free_lineaddress(char *(*lineaddress)[LINES]);
int ft_check_resolution(char *line);
t_parser_global ft_parse_resolution(char *line);
int ft_check_ambient(char *line);
t_parser_global ft_parse_ambient(char *line);
int ft_check_camera(char *line);
t_parser_global ft_parse_camera(char *line);
int ft_is_line_correct(char *line);
t_parser_global ft_parse_line(char *line, int parse_choice);
void ft_terminate_with_error(char *message, t_lineaddress *lineaddress, t_list_minirt **head, void (*ft_del_node_lstminirt)(void*));
int ft_check_light(char *line);
t_parser_global ft_parse_light(char *line);
int ft_check_plane(char *line);
t_parser_global ft_parse_plane(char *line);
int ft_check_sphere(char *line);
t_parser_global ft_parse_sphere(char *line);
int ft_check_square(char *line);
